modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/zsoltmolnarrr/Jewelry/issues"
license = "All Rights Reserved"

[[mods]]
modId = "jewelry"
version = "${version}"
displayName = "Jewelry (RPG Series)"
authors = "Daedelus"
description = '''
Find precious gems deep down, and craft them into powerful jewelry!
'''
logoFile = "icon.png"

[[dependencies.jewelry]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jewelry]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jewelry]]
modId = "spell_power"
type = "required"
versionRange = "[${spell_power_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jewelry]]
modId = "ranged_weapon_api"
type = "required"
versionRange = "[${ranged_weapon_api_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "jewelry.mixins.json"
